
FROM ruby:3.3.1

RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
  nodejs \
  libqt5webkit5-dev \
  && apt-get -q clean \
  && rm -rf /var/lib/apt/lists

WORKDIR /app

COPY Gemfile* ./

RUN bundle install

COPY . .

# Precompile assets for production
# RUN bundle exec rake assets:precompile

# Specify the command to run the application
CMD ["rails", "server", "-b", "0.0.0.0"]
